"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rl_policy_cmd_lcmt(object):

    __slots__ = ["timestamp_us", "sequence", "state_sequence", "status", "inference_time_ms", "action", "target_q"]

    __typenames__ = ["int64_t", "int64_t", "int64_t", "int32_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, [12], [12]]

    def __init__(self):
        self.timestamp_us = 0
        """ LCM Type: int64_t """
        self.sequence = 0
        """ LCM Type: int64_t """
        self.state_sequence = 0
        """ LCM Type: int64_t """
        self.status = 0
        """ LCM Type: int32_t """
        self.inference_time_ms = 0.0
        """ LCM Type: float """
        self.action = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.target_q = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(rl_policy_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqif", self.timestamp_us, self.sequence, self.state_sequence, self.status, self.inference_time_ms))
        buf.write(struct.pack('>12f', *self.action[:12]))
        buf.write(struct.pack('>12f', *self.target_q[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rl_policy_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rl_policy_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rl_policy_cmd_lcmt()
        self.timestamp_us, self.sequence, self.state_sequence, self.status, self.inference_time_ms = struct.unpack(">qqqif", buf.read(32))
        self.action = struct.unpack('>12f', buf.read(48))
        self.target_q = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rl_policy_cmd_lcmt in parents: return 0
        tmphash = (0xbf5cbf6ce5d11584) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rl_policy_cmd_lcmt._packed_fingerprint is None:
            rl_policy_cmd_lcmt._packed_fingerprint = struct.pack(">Q", rl_policy_cmd_lcmt._get_hash_recursive([]))
        return rl_policy_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rl_policy_cmd_lcmt._get_packed_fingerprint())[0]

