"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rl_robot_state_lcmt(object):

    __slots__ = ["timestamp_us", "sequence", "mode", "projected_gravity", "command", "q", "qd", "last_action"]

    __typenames__ = ["int64_t", "int64_t", "int32_t", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, [3], [3], [12], [12], [12]]

    def __init__(self):
        self.timestamp_us = 0
        """ LCM Type: int64_t """
        self.sequence = 0
        """ LCM Type: int64_t """
        self.mode = 0
        """ LCM Type: int32_t """
        self.projected_gravity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.command = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.q = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.qd = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.last_action = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(rl_robot_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqi", self.timestamp_us, self.sequence, self.mode))
        buf.write(struct.pack('>3f', *self.projected_gravity[:3]))
        buf.write(struct.pack('>3f', *self.command[:3]))
        buf.write(struct.pack('>12f', *self.q[:12]))
        buf.write(struct.pack('>12f', *self.qd[:12]))
        buf.write(struct.pack('>12f', *self.last_action[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rl_robot_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rl_robot_state_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rl_robot_state_lcmt()
        self.timestamp_us, self.sequence, self.mode = struct.unpack(">qqi", buf.read(20))
        self.projected_gravity = struct.unpack('>3f', buf.read(12))
        self.command = struct.unpack('>3f', buf.read(12))
        self.q = struct.unpack('>12f', buf.read(48))
        self.qd = struct.unpack('>12f', buf.read(48))
        self.last_action = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rl_robot_state_lcmt in parents: return 0
        tmphash = (0x87a3a7b249f75f56) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rl_robot_state_lcmt._packed_fingerprint is None:
            rl_robot_state_lcmt._packed_fingerprint = struct.pack(">Q", rl_robot_state_lcmt._get_hash_recursive([]))
        return rl_robot_state_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rl_robot_state_lcmt._get_packed_fingerprint())[0]

